### ISSUE TITLE
CM --> création possible seulement si CP et M existent, le formulaire est alors constitué  de deux séries d'onglets préremplis

### ISSUE THREAD

**Issue by alessio265** [HEG-Arc/MiCorr#103]

**Comment by cgaspoz** [comment]
Needs #104

**Comment by cgaspoz** [comment]
Il faut créer une strata métal
Et j'ai ensuite mis la possibilité de créer une CM depuis l'onglet "interface" de la couche métal
S'il n'y a pas de CP il en crée une et ensuite CM se base sur ces deux couches
J'avais mis un ascenseur pour définir le ratio CP/M

**Comment by cgaspoz** [comment]
@Tpower36, idem est-ce que l'on peut fermer?

**Comment by cdegrigny** [comment]
C�dric,



Pour moi oui,



Christian



Christian Degrigny

Enseignant chercheur / lecturer researcher

Haute Ecole Arc Conservation-restauration

Campus Arc 2, Espace de l'Europe 11

CH-2000 Neuch�tel

Tel +41 32 930 1919

Fax +41 32 930 1920

Internet www.he-arc.ch<http://www.he-arc.ch/>

Webpage http://people.he-arc.ch/christian.degrigny

________________________________
De : C�dric Gaspoz [notifications@github.com]
Envoy� : vendredi 17 juin 2016 16:04
� : HEG-Arc/MiCorr
Objet : Re: [HEG-Arc/MiCorr] CM --> cr�ation possible seulement si CP et M existent, le formulaire est alors constitu� de deux s�ries d'onglets pr�remplis (#103)


@Tpower36<https://github.com/Tpower36>, idem est-ce que l'on peut fermer?

�
