### ISSUE TITLE
Child Strata

### ISSUE THREAD

**Issue by cgaspoz** [HEG-Arc/MiCorr#106]
Les childs sont des zooms sur une couche particulière
Nommage pointé: CM1.CP1 / CM1.CP2 / ...
Afficher le dessin (sur/sous la stratigraphie principale)
![img_20160120_121951](https://cloud.githubusercontent.com/assets/438609/12447458/90ee91aa-bf70-11e5-932c-80b35583020b.jpg)

**Comment by cgaspoz** [comment]
@Tpower36 est-ce que l'on peut fermer?

**Comment by cdegrigny** [comment]
Oui,



Christian Degrigny

Enseignant chercheur / lecturer researcher

Haute Ecole Arc Conservation-restauration

Campus Arc 2, Espace de l'Europe 11

CH-2000 Neuch�tel

Tel +41 32 930 1919

Fax +41 32 930 1920

Internet www.he-arc.ch<http://www.he-arc.ch/>

Webpage http://people.he-arc.ch/christian.degrigny

________________________________
De : C�dric Gaspoz [notifications@github.com]
Envoy� : vendredi 17 juin 2016 16:03
� : HEG-Arc/MiCorr
Objet : Re: [HEG-Arc/MiCorr] Child Strata (#106)


@Tpower36<https://github.com/Tpower36> est-ce que l'on peut fermer?

�
