### ISSUE TITLE
le service /json/getstratigraphydetails ne retourne pas le Sub Sub CPRI microstructure aggregate composition

### ISSUE THREAD

**Issue by alessio265** [HEG-Arc/MiCorr#112]
le "Sub Sub CPRI microstructure aggregate composition" est bien stocké dans Neo4j, pourtant je ne le reçois pas dans les subcharacteristics...

**Comment by cgaspoz** [comment]
Voir si c'est encore d'actualité!

**Comment by cdegrigny** [comment]
C�dric,



Je crois que c'est corrig�.

Christian



Christian Degrigny

Enseignant chercheur / lecturer researcher

Haute Ecole Arc Conservation-restauration

Campus Arc 2, Espace de l'Europe 11

CH-2000 Neuch�tel

Tel +41 32 930 1919

Fax +41 32 930 1920

Internet www.he-arc.ch<http://www.he-arc.ch/>

Webpage http://people.he-arc.ch/christian.degrigny

________________________________
De : C�dric Gaspoz [notifications@github.com]
Envoy� : vendredi 17 juin 2016 15:59
� : HEG-Arc/MiCorr
Objet : Re: [HEG-Arc/MiCorr] le service /json/getstratigraphydetails ne retourne pas le Sub Sub CPRI microstructure aggregate composition (#112)


Voir si c'est encore d'actualit�!

�
