### ISSUE TITLE
Ajouter des caractéristiques de couleur : saturé/lavé (non-visible) et clair/foncé (visible)

### ISSUE THREAD

**Issue by micorr** [HEG-Arc/MiCorr#116]

**Comment by cgaspoz** [comment]
Regarder avec @cdegrigny ce qu'il faut faire avec ça...

**Comment by cdegrigny** [comment]
Cédric, l'idée ici était je suppose d'avoir des couleurs plus variées que celles existantes sous couleur dans l'onglet Morphologie des strates. Est-ce possible?

**Comment by cgaspoz** [comment]
Oui c'est possible. Est-ce que tu peux donner une liste des couleurs à utiliser à @alessio265 ?

**Comment by cgaspoz** [comment]
@cdegrigny si on ajoute une palette complète, on ne pourra plus faire de comparaison. Il faudrait nous donner une liste d'une dizaine de couleurs à ajouter et limiter ainsi le choix

**Comment by cdegrigny** [comment]
Cédric,



J'ai prévu d'ajouter 7 couleurs dans le spectre de couleurs actuelles des strates (voir document joint: croix rouges). J'ai indiqué avec une flèche rouge les nouvelles couleurs et ai modifié en noir le nom de certaines couleurs actuelles (croix noires).



Bien à toi,

Christian



Christian Degrigny

Enseignant chercheur / lecturer researcher

Haute Ecole Arc Conservation-restauration

Campus Arc 2, Espace de l'Europe 11

CH-2000 Neuchâtel

Tel +41 32 930 1919

Fax +41 32 930 1920

Internet www.he-arc.ch<http://www.he-arc.ch/>

Webpage http://people.he-arc.ch/christian.degrigny

________________________________
De : Cédric Gaspoz [notifications@github.com]
Envoyé : jeudi 23 juin 2016 16:14
À : HEG-Arc/MiCorr
Cc : Degrigny Christian; Mention
Objet : Re: [HEG-Arc/MiCorr] Ajouter des caractéristiques de couleur : saturé/lavé (non-visible) et clair/foncé (visible) (#116)


@cdegrigny<https://github.com/cdegrigny> si on ajoute une palette complète, on ne pourra plus faire de comparaison. Il faudrait nous donner une liste d'une dizaine de couleurs à ajouter et limiter ainsi le choix

**Comment by alessio265** [comment]
MATCH (c:Characteristic {uid:"yellowCharacteristic"}) WITH c as map CREATE (copy:Characteristic {uid:"darkRedCharacteristic",name:"dark red"}) SET copy.label = map.label, copy.name = 'dark red', copy.comparisonIndicator1 = map.comparisonIndicator1, copy.comparisonIndicator2 = map.comparisonIndicator2, copy.comparisonIndicator3 = map.comparisonIndicator3, copy.comparisonIndicator4 = map.comparisonIndicator4, copy.comparisonIndicator5 = map.comparisonIndicator5, copy.type = map.type, copy.order = map.order, copy.visible = map.visible, copy.version = map.version, copy.fullName = map.fullName, copy.description = map.description, copy.date = map.date RETURN copy

MATCH (c:Characteristic {uid:"darkRedCharacteristic"}), (f:Family {uid:"colourFamily"}) CREATE (f)-[:BELONGS_TO]->(c)
