### ISSUE TITLE
Tableau des comparaisons (stratigraphie)

### ISSUE THREAD

**Issue by cgaspoz** [HEG-Arc/MiCorr#122]
Ajouter la représentation graphique des stratigraphies dans le tableau des résultats de la comparaison.

**Comment by Tpower36** [comment]
Cette issue est n'est pas totalement résolue car après vérification, la requête de matching fait vraiment la comparaison avec toutes les strates de toutes les stratigraphies de l'artefact. On a donc aucun moyen de savoir avec quelle stratigraphie elle à matché.

Pour le moment j'affiche la première stratigraphie de l'artefact
