### ISSUE TITLE
Comparaison de stratigraphies

### ISSUE THREAD

**Issue by cgaspoz** [HEG-Arc/MiCorr#181]
Si la stratigraphie a trop d'attributs, la requête GET est trop longue et aucune comparaison ne peut être effectuée.

**Comment by cgaspoz** [comment]
Transformer la requête de GET à POST

**Comment by cgaspoz** [comment]
@cdegrigny C'est corrigé. Toutes les stratigraphies devraient pouvoir être comparées

**Comment by cdegrigny** [comment]
Bonsoir C�dric,


Je n'arrive pas � faire la comparaison avec les simples stratigraphies Metal2016 sous mon profil cdegrigny/HEAAArc1!


Je regarderai � nouveau cela demain.


Bien � toi,

Christian


Christian Degrigny

Enseignant chercheur / lecturer researcher

Haute Ecole Arc Conservation-restauration

Campus Arc 2, Espace de l'Europe 11

CH-2000 Neuch�tel

Tel +41 32 930 1919

Fax +41 32 930 1920

Internet www.he-arc.ch<http://www.he-arc.ch>

Webpage http://people.he-arc.ch/christian.degrigny


________________________________
De : C�dric Gaspoz <notifications@github.com>
Envoy� : dimanche 25 septembre 2016 19:49
� : HEG-Arc/MiCorr
Cc : Degrigny Christian; Mention
Objet : Re: [HEG-Arc/MiCorr] Comparaison de stratigraphies (#181)


@cdegrigny<https://github.com/cdegrigny> C'est corrig�. Toutes les stratigraphies devraient pouvoir �tre compar�es

-

**Comment by cdegrigny** [comment]
C�dric,


C'est bon. Pardon. Par contre, je retombe toujours sur d'anciennes stratigraphies lorsque je fais la comparaison via "Find similar". Il ne s'agit pas des stratigraphies actuelles stock�es sous micorr / heg7cool. Est-il possible de remettre � jour ces stratigraphies?


Bien � toi,

Christian


Christian Degrigny

Enseignant chercheur / lecturer researcher

Haute Ecole Arc Conservation-restauration

Campus Arc 2, Espace de l'Europe 11

CH-2000 Neuch�tel

Tel +41 32 930 1919

Fax +41 32 930 1920

Internet www.he-arc.ch<http://www.he-arc.ch>

Webpage http://people.he-arc.ch/christian.degrigny


________________________________
De : Degrigny Christian
Envoy� : dimanche 25 septembre 2016 20:52
� : HEG-Arc/MiCorr; HEG-Arc/MiCorr
Cc : Mention
Objet : RE: [HEG-Arc/MiCorr] Comparaison de stratigraphies (#181)


Bonsoir C�dric,


Je n'arrive pas � faire la comparaison avec les simples stratigraphies Metal2016 sous mon profil cdegrigny/HEAAArc1!


Je regarderai � nouveau cela demain.


Bien � toi,

Christian


Christian Degrigny

Enseignant chercheur / lecturer researcher

Haute Ecole Arc Conservation-restauration

Campus Arc 2, Espace de l'Europe 11

CH-2000 Neuch�tel

Tel +41 32 930 1919

Fax +41 32 930 1920

Internet www.he-arc.ch<http://www.he-arc.ch>

Webpage http://people.he-arc.ch/christian.degrigny


________________________________
De : C�dric Gaspoz <notifications@github.com>
Envoy� : dimanche 25 septembre 2016 19:49
� : HEG-Arc/MiCorr
Cc : Degrigny Christian; Mention
Objet : Re: [HEG-Arc/MiCorr] Comparaison de stratigraphies (#181)


@cdegrigny<https://github.com/cdegrigny> C'est corrig�. Toutes les stratigraphies devraient pouvoir �tre compar�es

-
