### ISSUE TITLE
Strata: si on ajoute une propriété la "ligne" de séparation disparaît entre les couches

### ISSUE THREAD

**Issue by cgaspoz** [HEG-Arc/MiCorr#59]

**Comment by cgaspoz** [comment]
Mettre une bordure noire par défaut si on n'a pas l'information avant le rendering, on ajoute la bordure

**Comment by cgaspoz** [comment]
Quand on déplace la strate, la ligne disparaît

**Comment by alessio265** [comment]
La ligne qui restait affichée sur le bas de la stratigraphie était un 'bug' dû au fait qu'on ne rafraîchissait pas le dessin. Il n'y a actuellement plus de ligne (supérieure) lorsque l'on ajoute une nouvelle strate, puisque l'interface n'est pas encore définie!
