### ISSUE TITLE
Find similar

### ISSUE THREAD

**Issue by cgaspoz** [HEG-Arc/MiCorr#68]
Afficher la liste des artefacts (search tool) à la place de la liste de matching

**Comment by cgaspoz** [comment]
Récupérer la liste du matching depuis py2neo/django
Pour chaque UID de stratigraphie, rechercher l'ID de l'artefact (fiche)
Retourner un tableau avec la liste des fiches + info matching

**Comment by cgaspoz** [comment]
Genoud Sierre?

**Comment by micorr** [comment]
Mail envoyé, en attente de réponse

**Comment by cgaspoz** [comment]
Reprendre contact avec Sierre et relancer le processus...
