### ISSUE TITLE
Strata: exporter to PNG ne fonctionne pas

### ISSUE THREAD

**Issue by cgaspoz** [HEG-Arc/MiCorr#73]

**Comment by cgaspoz** [comment]
Tester avec browsers... et trouver celui qui marche

**Comment by cgaspoz** [comment]
Attendre pour voir si on bascule ça directement sur le serveur (génération du PNG)

**Comment by Tpower36** [comment]
J'ai finalement réussi à importer le contenu des fichiers SVG des calques directement dans le SVG généré par node JS. Par contre, la  librairie librsvg que j'ai utilisé pour faire la conversion en PNG ne supporte pas la plus grande partie des calques, il faudra donc utiliser une autre librairie pour faire les conversions. Je m'occupe encore de ça après avoir rédigé mon rapport de TB si il me reste un peu de temps.

**Comment by Tpower36** [comment]
Note pour déploiement: La version de inkscape installée sur le serveur doit absolument être la version 0.91 pour que l'export en PNG fonctionne correctement. Avec l'ancienne version, les tailles et les positions des images sont fausses.
