### ISSUE TITLE
Strata: ajouter les nuances de couleur

### ISSUE THREAD

**Issue by cgaspoz** [HEG-Arc/MiCorr#75]
Ajouter light, middle, dark pour:
- vert
- rouge
- bleu

**Comment by cgaspoz** [comment]
@cdegrigny qu'est-ce qu'il faut réellement mettre?

**Comment by cdegrigny** [comment]
Bonjour Cédric,
L'idée était d'apporter des nuances aux couleurs proposées (et en particulier pour les vert, rouge et bleu). En effet pour les alliages cuivreux, on a plusieurs types de produits de corrosion qui sont bleu clair, bleu foncé ou vert clair, vert foncé. Aujourd'hui on ne peut pas les distinguer dans une même stratigraphie alors que la couleur est bien distincte entre ces strates.
Christian
