### ISSUE TITLE
Strata: ajouter une icône avec un oeil pour les caractéristiques qui sont effectivement affichées

### ISSUE THREAD

**Issue by cgaspoz** [HEG-Arc/MiCorr#82]

**Comment by cgaspoz** [comment]
Ajouter un attribut dans Neo4J @antoinerosselet 
Afficher l'attribut dans l'interface @alessio265

**Comment by micorr** [comment]
Dans Neo4j, un boolean "visible" a été ajouté à toutes les caracteristiques
