### ISSUE TITLE
le service getDeailedStratigraphy ne retourne pas "cpCompositionExtensionFamily"

### ISSUE THREAD

**Issue by alessio265** [HEG-Arc/MiCorr#97]
ex : /micorr/json/getstratigraphydetails/test_stratigraphy3

j'ai besoin de "cpCompositionExtensionFamily" pour afficher la PickList

**Comment by cgaspoz** [comment]
Check avec Alessio

**Comment by cgaspoz** [comment]
@alessio265 est-ce que l'on peut fermer?
